spring.application.name=vehicle-booking-system
spring.profiles.active=dev
booking.expiration.pending-payment-timeout=15m
booking.expiration.cleanup-interval=5m

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=when-authorized
